/** @type {import('tailwindcss').Config} */
const plugin = require('tailwindcss/plugin');

export default {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  safelist: [
    // Explicit brand color classes - patterns weren't working, using explicit list
    // Login page brand colors
    'bg-brand-primary-500', 'bg-brand-primary-600', 'bg-brand-primary-700', 'bg-brand-primary-950',
    'bg-brand-accent-500', 'bg-brand-accent-600', 'bg-brand-teal-500', 'bg-brand-teal-600',
    'text-brand-primary-200', 'text-brand-primary-300', 'text-brand-primary-400',
    'from-brand-primary-400', 'from-brand-primary-500', 'from-brand-primary-600',
    'to-brand-accent-400', 'to-brand-accent-600', 'to-brand-teal-600',
    'via-brand-primary-950', 'from-gray-950', 'to-gray-950',
    'from-warning-400', 'to-warning-600', 'from-success-400', 'to-success-600',
    'text-warning-400', 'shadow-primary-lg',
    // Additional brand colors for components
    'bg-brand-primary-100', 'bg-brand-primary-200', 'bg-brand-primary-300', 'bg-brand-primary-400',
    'bg-brand-primary-800', 'bg-brand-primary-900',
    'bg-brand-accent-100', 'bg-brand-accent-200', 'bg-brand-accent-300', 'bg-brand-accent-400',
    'text-brand-primary-600', 'text-brand-primary-700', 'text-brand-primary-800',
    'text-brand-accent-400', 'text-brand-accent-600', 'text-brand-teal-600',
    'from-brand-accent-400', 'from-brand-teal-400', 'from-brand-teal-500',
    'to-brand-primary-700', 'to-brand-accent-700',
    'border-brand-primary-200', 'border-brand-primary-700',
    'hover:from-brand-primary-700', 'hover:to-brand-accent-700',
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        // Keep existing shadcn/ui mappings for backward compatibility
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },

        // CoreFlow360 Design System - Brand Colors from design-tokens.css
        'brand-primary': {
          50: 'var(--brand-primary-50)',
          100: 'var(--brand-primary-100)',
          200: 'var(--brand-primary-200)',
          300: 'var(--brand-primary-300)',
          400: 'var(--brand-primary-400)',
          500: 'var(--brand-primary-500)',
          600: 'var(--brand-primary-600)',
          700: 'var(--brand-primary-700)',
          800: 'var(--brand-primary-800)',
          900: 'var(--brand-primary-900)',
          950: 'var(--brand-primary-950)',
          DEFAULT: 'var(--brand-primary-600)', // Trust Blue
        },
        'brand-accent': {
          50: 'var(--brand-accent-50)',
          100: 'var(--brand-accent-100)',
          200: 'var(--brand-accent-200)',
          300: 'var(--brand-accent-300)',
          400: 'var(--brand-accent-400)',
          500: 'var(--brand-accent-500)',
          600: 'var(--brand-accent-600)',
          700: 'var(--brand-accent-700)',
          800: 'var(--brand-accent-800)',
          900: 'var(--brand-accent-900)',
          950: 'var(--brand-accent-950)',
          DEFAULT: 'var(--brand-accent-600)',
        },
        'brand-teal': {
          50: 'var(--brand-teal-50)',
          100: 'var(--brand-teal-100)',
          200: 'var(--brand-teal-200)',
          300: 'var(--brand-teal-300)',
          400: 'var(--brand-teal-400)',
          500: 'var(--brand-teal-500)',
          600: 'var(--brand-teal-600)',
          700: 'var(--brand-teal-700)',
          800: 'var(--brand-teal-800)',
          900: 'var(--brand-teal-900)',
          950: 'var(--brand-teal-950)',
          DEFAULT: 'var(--brand-teal-600)',
        },

        // Semantic Colors from design-tokens.css
        success: {
          50: 'var(--semantic-success-50)',
          100: 'var(--semantic-success-100)',
          200: 'var(--semantic-success-200)',
          300: 'var(--semantic-success-300)',
          400: 'var(--semantic-success-400)',
          500: 'var(--semantic-success-500)',
          600: 'var(--semantic-success-600)',
          700: 'var(--semantic-success-700)',
          800: 'var(--semantic-success-800)',
          900: 'var(--semantic-success-900)',
          DEFAULT: 'var(--semantic-success-500)',
        },
        warning: {
          50: 'var(--semantic-warning-50)',
          100: 'var(--semantic-warning-100)',
          200: 'var(--semantic-warning-200)',
          300: 'var(--semantic-warning-300)',
          400: 'var(--semantic-warning-400)',
          500: 'var(--semantic-warning-500)',
          600: 'var(--semantic-warning-600)',
          700: 'var(--semantic-warning-700)',
          800: 'var(--semantic-warning-800)',
          900: 'var(--semantic-warning-900)',
          DEFAULT: 'var(--semantic-warning-500)',
        },
        error: {
          50: 'var(--semantic-error-50)',
          100: 'var(--semantic-error-100)',
          200: 'var(--semantic-error-200)',
          300: 'var(--semantic-error-300)',
          400: 'var(--semantic-error-400)',
          500: 'var(--semantic-error-500)',
          600: 'var(--semantic-error-600)',
          700: 'var(--semantic-error-700)',
          800: 'var(--semantic-error-800)',
          900: 'var(--semantic-error-900)',
          DEFAULT: 'var(--semantic-error-500)',
        },
        info: {
          50: 'var(--semantic-info-50)',
          100: 'var(--semantic-info-100)',
          200: 'var(--semantic-info-200)',
          300: 'var(--semantic-info-300)',
          400: 'var(--semantic-info-400)',
          500: 'var(--semantic-info-500)',
          600: 'var(--semantic-info-600)',
          700: 'var(--semantic-info-700)',
          800: 'var(--semantic-info-800)',
          900: 'var(--semantic-info-900)',
          DEFAULT: 'var(--semantic-info-500)',
        },

        // Neutral grays from design-tokens.css
        neutral: {
          0: 'var(--neutral-0)',
          50: 'var(--neutral-50)',
          100: 'var(--neutral-100)',
          200: 'var(--neutral-200)',
          300: 'var(--neutral-300)',
          400: 'var(--neutral-400)',
          500: 'var(--neutral-500)',
          600: 'var(--neutral-600)',
          700: 'var(--neutral-700)',
          800: 'var(--neutral-800)',
          900: 'var(--neutral-900)',
          950: 'var(--neutral-950)',
          1000: 'var(--neutral-1000)',
        },
        gray: {
          50: 'var(--gray-50)',
          100: 'var(--gray-100)',
          200: 'var(--gray-200)',
          300: 'var(--gray-300)',
          400: 'var(--gray-400)',
          500: 'var(--gray-500)',
          600: 'var(--gray-600)',
          700: 'var(--gray-700)',
          800: 'var(--gray-800)',
          900: 'var(--gray-900)',
          950: 'var(--gray-950)',
          DEFAULT: 'var(--gray-500)',
        },

        // TailAdmin Dashboard Colors
        boxdark: '#24303F',
        'boxdark-2': '#1A222C',
        strokedark: '#2E3A47',
        'form-strokedark': '#3d4d60',
        'form-input': '#1d2a39',
        bodydark: '#AEB7C0',
        bodydark1: '#DEE4EE',
        bodydark2: '#8A99AF',
        'meta-1': '#DC3545',
        'meta-2': '#EFF2F7',
        'meta-3': '#10B981',
        'meta-4': '#313D4A',
        'meta-5': '#259AE6',
        'meta-6': '#FFBA00',
        'meta-7': '#FF6766',
        'meta-8': '#F0950C',
        'meta-9': '#E5E7EB',
        'meta-10': '#219653',
        graydark: '#333A48',
        'gray-2': '#F7F9FC',
        stroke: '#E2E8F0',
        danger: '#D34053',
      },
      borderRadius: {
        lg: "var(--radius-lg)",
        md: "var(--radius-md)",
        sm: "var(--radius-sm)",
        xl: "var(--radius-xl)",
        '2xl': "var(--radius-2xl)",
        '3xl': "var(--radius-3xl)",
        '4xl': "var(--radius-4xl)",
        full: "var(--radius-full)",
      },
      fontFamily: {
        sans: 'var(--font-sans)'.split(', '),
        mono: 'var(--font-mono)'.split(', '),
      },
      fontSize: {
        xs: 'var(--text-xs)',
        sm: 'var(--text-sm)',
        base: 'var(--text-base)',
        lg: 'var(--text-lg)',
        xl: 'var(--text-xl)',
        '2xl': 'var(--text-2xl)',
        '3xl': 'var(--text-3xl)',
        '4xl': 'var(--text-4xl)',
        '5xl': 'var(--text-5xl)',
        '6xl': 'var(--text-6xl)',
        '7xl': 'var(--text-7xl)',
        '8xl': 'var(--text-8xl)',
      },
      spacing: {
        0: 'var(--space-0)',
        px: 'var(--space-px)',
        0.5: 'var(--space-0\.5)',
        1: 'var(--space-1)',
        1.5: 'var(--space-1\.5)',
        2: 'var(--space-2)',
        2.5: 'var(--space-2\.5)',
        3: 'var(--space-3)',
        3.5: 'var(--space-3\.5)',
        4: 'var(--space-4)',
        5: 'var(--space-5)',
        6: 'var(--space-6)',
        7: 'var(--space-7)',
        8: 'var(--space-8)',
        9: 'var(--space-9)',
        10: 'var(--space-10)',
        11: 'var(--space-11)',
        12: 'var(--space-12)',
        14: 'var(--space-14)',
        16: 'var(--space-16)',
        20: 'var(--space-20)',
        24: 'var(--space-24)',
        28: 'var(--space-28)',
        32: 'var(--space-32)',
        36: 'var(--space-36)',
        40: 'var(--space-40)',
        44: 'var(--space-44)',
        48: 'var(--space-48)',
        52: 'var(--space-52)',
        56: 'var(--space-56)',
        60: 'var(--space-60)',
        64: 'var(--space-64)',
        72: 'var(--space-72)',
        80: 'var(--space-80)',
        96: 'var(--space-96)',
      },
      boxShadow: {
        xs: 'var(--shadow-xs)',
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
        '2xl': 'var(--shadow-2xl)',
        '3xl': 'var(--shadow-3xl)',
        'primary-sm': 'var(--shadow-primary-sm)',
        'primary-md': 'var(--shadow-primary-md)',
        'primary-lg': 'var(--shadow-primary-lg)',
        'primary-xl': 'var(--shadow-primary-xl)',
        inner: 'var(--shadow-inner-md)',
        none: 'none',
      },
      animation: {
        "fade-in": "fadeIn var(--duration-base) var(--ease-in-out)",
        "fade-out": "fadeOut var(--duration-base) var(--ease-in-out)",
        "slide-in": "slideIn var(--duration-base) var(--ease-out)",
        "slide-out": "slideOut var(--duration-base) var(--ease-in)",
        "bounce-in": "bounceIn var(--duration-moderate) var(--ease-bounce)",
        "scale-in": "scaleIn var(--duration-fast) var(--ease-out)",
        "pulse-slow": "pulse var(--duration-slowest) var(--ease-in-out) infinite",
      },
      backdropBlur: {
        xs: '2px',
        sm: 'var(--backdrop-blur-sm)',
        md: 'var(--backdrop-blur-md)',
        lg: 'var(--backdrop-blur-lg)',
        xl: 'var(--backdrop-blur-xl)',
      },
      screens: {
        xs: "475px",
      },
    },
  },
  plugins: [
    plugin(function({ addUtilities }) {
      addUtilities({
        // Semantic background utilities
        '.bg-surface': { 'background-color': 'var(--bg-surface)' },
        '.bg-elevated': { 'background-color': 'var(--bg-elevated)' },
        '.bg-subtle': { 'background-color': 'var(--bg-subtle)' },
        '.bg-base': { 'background-color': 'var(--bg-base)' },

        // Semantic text utilities
        '.text-primary-token': { color: 'var(--text-primary)' },
        '.text-secondary-token': { color: 'var(--text-secondary)' },
        '.text-tertiary': { color: 'var(--text-tertiary)' },
        '.text-muted-token': { color: 'var(--text-muted)' },
        '.text-inverse': { color: 'var(--text-inverse)' },

        // Semantic border utilities
        '.border-subtle': { 'border-color': 'var(--border-subtle)' },
        '.border-default-token': { 'border-color': 'var(--border-default)' },
        '.border-strong': { 'border-color': 'var(--border-strong)' },
      });
    }),
  ],
}