import js from '@eslint/js';
import tsParser from '@typescript-eslint/parser';
import tsPlugin from '@typescript-eslint/eslint-plugin';

export default [
  {
    ignores: [
      'node_modules/',
      'dist/',
      '.wrangler/',
      'coverage/',
      '__graveyard__/',
      '**/*-old.ts', // Ignore deprecated/old files
      '**/*-old.js',
    ]
  },
  js.configs.recommended,
  {
    files: ['**/*.ts', '**/*.tsx'],
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        ecmaVersion: 2022,
        sourceType: 'module'
      },
      globals: {
        // Cloudflare Workers + Browser globals
        console: 'readonly',
        fetch: 'readonly',
        Request: 'readonly',
        Response: 'readonly',
        Headers: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        FormData: 'readonly',
        Blob: 'readonly',
        File: 'readonly',
        ReadableStream: 'readonly',
        WritableStream: 'readonly',
        TransformStream: 'readonly',
        crypto: 'readonly',
        SubtleCrypto: 'readonly',
        CryptoKey: 'readonly',
        TextEncoder: 'readonly',
        TextDecoder: 'readonly',
        atob: 'readonly',
        btoa: 'readonly',
        setTimeout: 'readonly',
        setInterval: 'readonly',
        clearTimeout: 'readonly',
        clearInterval: 'readonly',
        queueMicrotask: 'readonly',
        structuredClone: 'readonly',
        performance: 'readonly',
        navigator: 'readonly',
        window: 'readonly',
        document: 'readonly',
        // WebGPU
        GPUDevice: 'readonly',
        GPUAdapter: 'readonly',
        GPUComputePipeline: 'readonly',
        GPUBuffer: 'readonly',
        GPUBufferUsage: 'readonly',
        GPUMapMode: 'readonly',
        GPUQuerySet: 'readonly',
        // Node.js
        process: 'readonly',
        Buffer: 'readonly',
        global: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        module: 'readonly',
        require: 'readonly',
        exports: 'readonly',
        setImmediate: 'readonly',
        clearImmediate: 'readonly',
        NodeJS: 'readonly',
        // Cloudflare Workers specific
        MessageBatch: 'readonly',
        ScheduledController: 'readonly',
        ScheduledEvent: 'readonly',
        ExecutionContext: 'readonly',
        DurableObjectState: 'readonly',
        DurableObjectNamespace: 'readonly',
        DurableObjectStorage: 'readonly',
        KVNamespace: 'readonly',
        R2Bucket: 'readonly',
        D1Database: 'readonly',
        Queue: 'readonly',
        Ai: 'readonly',
        AnalyticsEngineDataset: 'readonly',
        // Web APIs
        WebSocket: 'readonly',
        WebSocketPair: 'readonly',
        AbortController: 'readonly',
        AbortSignal: 'readonly',
        BufferSource: 'readonly',
        RequestInit: 'readonly',
        HeadersInit: 'readonly',
        BodyInit: 'readonly',
        WritableStreamDefaultWriter: 'readonly',
        ReadableStreamDefaultController: 'readonly',
        CompressionStream: 'readonly',
        DecompressionStream: 'readonly',
        HTMLInputElement: 'readonly',
        HTMLTextAreaElement: 'readonly',
        HTMLAnchorElement: 'readonly',
        CustomEvent: 'readonly',
        Event: 'readonly',
        EventTarget: 'readonly',
        EventSource: 'readonly',
        MouseEvent: 'readonly',
        KeyboardEvent: 'readonly',
        MessageEvent: 'readonly',
        PerformanceNavigationTiming: 'readonly',
        PerformanceObserver: 'readonly',
        DOMRect: 'readonly',
        Image: 'readonly',
        Cache: 'readonly',
        caches: 'readonly',
        screen: 'readonly',
        self: 'readonly',
        Worker: 'readonly',
        WorkerGlobalScope: 'readonly',
        Window: 'readonly',
        Document: 'readonly',
        Console: 'readonly',
        // Cloudflare-specific types
        DurableObject: 'readonly',
        DurableObjectId: 'readonly',
        D1Result: 'readonly',
        // Third-party libraries
        XLSX: 'readonly',
        jsPDF: 'readonly',
        ChartJSNodeCanvas: 'readonly',
        // Application classes (to be imported properly later)
        SqlStorage: 'readonly',
        SSEStreamManager: 'readonly',
        SSEStreamController: 'readonly',
        AIStreamAdapter: 'readonly',
        StreamMetricsCollector: 'readonly',
        Deno: 'readonly',
        Env: 'readonly',
      }
    },
    plugins: {
      '@typescript-eslint': tsPlugin
    },
    rules: {
      ...tsPlugin.configs.recommended.rules,
      'no-unused-vars': 'off',
      '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/ban-ts-comment': 'off',
      '@typescript-eslint/no-var-requires': 'off',
      '@typescript-eslint/ban-types': 'off',
      '@typescript-eslint/no-this-alias': 'off',
      '@typescript-eslint/no-loss-of-precision': 'off',
      'no-console': 'warn',
      'no-empty': 'off',
      'no-useless-escape': 'off',
      'no-control-regex': 'off',
      'no-useless-catch': 'off',
      'no-case-declarations': 'off',
      'no-unreachable': 'off',
      'no-constant-condition': 'off',
      'no-prototype-builtins': 'off',
      'no-loss-of-precision': 'off',
      'no-this-alias': 'off',
      'no-redeclare': 'off',
      'no-dupe-class-members': 'off',
      'no-var-requires': 'off'
    }
  },
  {
    files: ['**/*.js', '**/*.jsx'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        console: 'readonly',
        process: 'readonly',
        Buffer: 'readonly',
        global: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        module: 'readonly',
        require: 'readonly',
        exports: 'readonly',
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        fetch: 'readonly',
        Response: 'readonly',
        Request: 'readonly',
        Headers: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        WebSocket: 'readonly',
      }
    },
    rules: {
      'no-console': 'warn',
      'no-debugger': 'warn',
      'prefer-const': 'warn',
      'no-var': 'error',
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }]
    }
  },
  {
    files: [
      '**/*.test.ts',
      '**/*.test.tsx',
      '**/*.spec.ts',
      'tests/**/*.ts',
      'src/tests/**/*.ts'
    ],
    languageOptions: {
      globals: {
        describe: 'readonly',
        it: 'readonly',
        expect: 'readonly',
        test: 'readonly',
        beforeEach: 'readonly',
        afterEach: 'readonly',
        beforeAll: 'readonly',
        afterAll: 'readonly',
        vi: 'readonly',
        jest: 'readonly',
        task: 'readonly',
        console: 'readonly',
        global: 'readonly',
        Request: 'readonly',
        Response: 'readonly',
        Cache: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        fetch: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        Headers: 'readonly',
        crypto: 'readonly',
        TextEncoder: 'readonly',
        TextDecoder: 'readonly',
        Buffer: 'readonly',
        process: 'readonly'
      }
    },
    rules: {
      'no-console': 'off',
      '@typescript-eslint/no-unused-vars': 'off'
    }
  }
];
