name = "coreflow360-v4-dev"
main = "src/index.minimal-test.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[env.development]
name = "coreflow360-v4-dev"
vars = { ENVIRONMENT = "development", LOG_LEVEL = "debug", SENTRY_ENVIRONMENT = "development" }

# D1 Database bindings - Development
[[d1_databases]]
binding = "DB"
database_name = "coreflow360-agents"
database_id = "c56bb204-78bc-4357-a704-419aa9f11e6f"
migrations_dir = "database/migrations"

[[d1_databases]]
binding = "DB_MAIN"
database_name = "coreflow360-agents"
database_id = "c56bb204-78bc-4357-a704-419aa9f11e6f"
migrations_dir = "database/migrations"

[[d1_databases]]
binding = "DB_ANALYTICS"
database_name = "mustbeviral-db"
database_id = "4cdeab75-a1b4-477e-a92c-de996065578c"

# KV Namespace bindings - Development
[[kv_namespaces]]
binding = "KV_CACHE"
id = "62253644abcf4ce78558fbd764b366fb"
preview_id = "dev-kv-cache"

[[kv_namespaces]]
binding = "KV_SESSION"
id = "bd87c1fb6fd34a21b47e6cdbdd5a20ae"
preview_id = "dev-kv-session"

[[kv_namespaces]]
binding = "KV_RATE_LIMIT_METRICS"
id = "rate-limit-metrics-namespace"
preview_id = "dev-rate-limit"

[[kv_namespaces]]
binding = "KV_AUTH"
id = "auth-namespace"
preview_id = "dev-auth"

# Rate Limiter binding
[[rate_limiters]]
binding = "RATE_LIMITER"
namespace_id = "coreflow360_rate_limiter"

# Durable Objects
[[durable_objects.bindings]]
name = "RATE_LIMITER_DO"
class_name = "AdvancedRateLimiterDO"

# R2 Bucket bindings - Development
[[r2_buckets]]
binding = "R2_DOCUMENTS"
bucket_name = "coreflow360-documents"

[[r2_buckets]]
binding = "R2_BACKUPS"
bucket_name = "coreflow360-backups"

# AI binding
[ai]
binding = "AI"

# Development variables
[vars]
APP_NAME = "CoreFlow360 V4 Dev"
API_VERSION = "v4-dev"
LOG_LEVEL = "debug"
ENVIRONMENT = "development"
API_BASE_URL = "http://localhost:8787"
ALLOWED_ORIGINS = "http://localhost:3000,http://localhost:3001,http://localhost:8787"

[observability]
enabled = true
head_sampling_rate = 1.0

[placement]
mode = "smart"

# Development server configuration
[dev]
port = 8787
local_protocol = "http"
upstream_protocol = "https"
ip = "0.0.0.0"

# Secrets (add via wrangler secret put in dev):
# AUTH_SECRET
# ENCRYPTION_KEY
# JWT_SECRET
# ANTHROPIC_API_KEY
# OPENAI_API_KEY
# STRIPE_SECRET_KEY
# EMAIL_API_KEY
# SENTRY_DSN