name = "coreflow360-v4"
main = "src/index.minimal.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "coreflow360-v4-prod"
vars = { ENVIRONMENT = "production", LOG_LEVEL = "warn", SENTRY_ENVIRONMENT = "production" }

[env.staging]
name = "coreflow360-v4-staging"
vars = { ENVIRONMENT = "staging", LOG_LEVEL = "info", SENTRY_ENVIRONMENT = "staging" }

[env.development]
name = "coreflow360-v4-dev"
vars = { ENVIRONMENT = "development", LOG_LEVEL = "debug", SENTRY_ENVIRONMENT = "development" }

# D1 Database bindings - Updated with real database IDs
[[d1_databases]]
binding = "DB"
database_name = "coreflow360-agents"
database_id = "c56bb204-78bc-4357-a704-419aa9f11e6f"
migrations_dir = "database/migrations"

[[d1_databases]]
binding = "DB_ANALYTICS"
database_name = "mustbeviral-db"
database_id = "4cdeab75-a1b4-477e-a92c-de996065578c"

# KV Namespace bindings
[[kv_namespaces]]
binding = "KV_CACHE"
id = "62253644abcf4ce78558fbd764b366fb"

[[kv_namespaces]]
binding = "KV_SESSION"
id = "bd87c1fb6fd34a21b47e6cdbdd5a20ae"

# Queue bindings (Note: Requires paid Cloudflare plan)
# [[queues.producers]]
# binding = "TASK_QUEUE"
# queue = "coreflow360-tasks"

# [[queues.producers]]
# binding = "EMAIL_QUEUE"
# queue = "coreflow360-emails"

# R2 Bucket bindings
[[r2_buckets]]
binding = "R2_DOCUMENTS"
bucket_name = "coreflow360-documents"

[[r2_buckets]]
binding = "R2_BACKUPS"
bucket_name = "coreflow360-backups"

# AI binding
[ai]
binding = "AI"

# Environment variables
[vars]
APP_NAME = "CoreFlow360 V4"
API_VERSION = "v4"
LOG_LEVEL = "info"
ENVIRONMENT = "development"

[observability]
enabled = true
head_sampling_rate = 0.1

[placement]
mode = "smart"

# CPU and memory limits (requires paid plan)
# [limits]
# cpu_ms = 50000
# memory_mb = 128

# Secrets to be added via wrangler secret put:
# AUTH_SECRET - JWT signing secret
# ENCRYPTION_KEY - Data encryption key
# JWT_SECRET - JWT token secret
# STRIPE_SECRET_KEY - Stripe payment processing
# OPENAI_API_KEY - OpenAI API access
# EMAIL_API_KEY - Email service API key
# SENTRY_DSN - Sentry error tracking DSN