# Security Policy for CoreFlow360 V4 Docker Deployment
# Enterprise-grade security configuration

version: '3.8'

# Security policies for containers
security_policies:
  # Container security
  containers:
    - name: "coreflow360-app"
      security_context:
        run_as_non_root: true
        run_as_user: 1001
        run_as_group: 1001
        read_only_root_filesystem: true
        allow_privilege_escalation: false
        capabilities:
          drop:
            - ALL
          add:
            - NET_BIND_SERVICE
      resources:
        limits:
          memory: "512Mi"
          cpu: "500m"
        requests:
          memory: "256Mi"
          cpu: "250m"
      security_opt:
        - no-new-privileges:true
        - seccomp:unconfined
      tmpfs:
        - /tmp
        - /app/logs

  # Network security
  networks:
    - name: "frontend"
      policy: "isolated"
      ingress:
        - from: "internet"
          ports: [80, 443]
        - from: "backend"
          ports: [3000]
    - name: "backend"
      policy: "private"
      ingress:
        - from: "frontend"
          ports: [3000, 5432, 6379]
    - name: "monitoring"
      policy: "private"
      ingress:
        - from: "backend"
          ports: [9090, 3002, 3100]

  # Secrets management
  secrets:
    - name: "postgres_password"
      type: "opaque"
      data:
        password: "base64_encoded_password"
    - name: "jwt_secret"
      type: "opaque"
      data:
        secret: "base64_encoded_jwt_secret"
    - name: "encryption_key"
      type: "opaque"
      data:
        key: "base64_encoded_encryption_key"

  # Pod security standards
  pod_security_standards:
    level: "restricted"
    version: "latest"
    exemptions:
      namespaces: ["kube-system", "kube-public"]
      runtimeClasses: []
      users: []
      usernames: []

  # Network policies
  network_policies:
    - name: "deny-all-ingress"
      spec:
        podSelector: {}
        policyTypes:
          - Ingress
    - name: "allow-frontend-to-backend"
      spec:
        podSelector:
          matchLabels:
            app: coreflow360-app
        policyTypes:
          - Ingress
        ingress:
          - from:
              - podSelector:
                  matchLabels:
                    app: coreflow360-frontend
            ports:
              - protocol: TCP
                port: 3000

  # RBAC policies
  rbac:
    roles:
      - name: "coreflow360-reader"
        rules:
          - apiGroups: [""]
            resources: ["pods", "services", "configmaps"]
            verbs: ["get", "list", "watch"]
      - name: "coreflow360-writer"
        rules:
          - apiGroups: [""]
            resources: ["pods", "services", "configmaps"]
            verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Security scanning
  security_scanning:
    enabled: true
    tools:
      - name: "trivy"
        schedule: "0 2 * * *"  # Daily at 2 AM
        severity_threshold: "HIGH"
      - name: "clair"
        schedule: "0 3 * * *"  # Daily at 3 AM
        severity_threshold: "CRITICAL"

  # Compliance
  compliance:
    standards:
      - "SOC2"
      - "ISO27001"
      - "PCI-DSS"
    controls:
      - name: "encryption_at_rest"
        status: "implemented"
      - name: "encryption_in_transit"
        status: "implemented"
      - name: "access_control"
        status: "implemented"
      - name: "audit_logging"
        status: "implemented"
