/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoiceRouteImport } from './routes/voice'
import { Route as TestRouteImport } from './routes/test'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as EmailRouteImport } from './routes/email'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as MarketingIndexRouteImport } from './routes/marketing.index'
import { Route as FinanceIndexRouteImport } from './routes/finance/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as CrmIndexRouteImport } from './routes/crm/index'
import { Route as SettingsSecurityRouteImport } from './routes/settings/security'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as SettingsBillingRouteImport } from './routes/settings/billing'
import { Route as MarketingProductsRouteImport } from './routes/marketing.products'
import { Route as FinanceInvoicesRouteImport } from './routes/finance/invoices'
import { Route as FinanceExpensesRouteImport } from './routes/finance/expenses'
import { Route as ErrorErrorRouteImport } from './routes/error/error'
import { Route as Error404RouteImport } from './routes/error/404'
import { Route as DashboardPortfolioRouteImport } from './routes/dashboard/portfolio'
import { Route as CrmDealsRouteImport } from './routes/crm/deals'
import { Route as CrmContactsRouteImport } from './routes/crm/contacts'
import { Route as CrmCompaniesRouteImport } from './routes/crm/companies'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth/verify-email'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as DashboardMigrationIndexRouteImport } from './routes/dashboard/migration/index'
import { Route as DashboardCrmIndexRouteImport } from './routes/dashboard/crm/index'
import { Route as DashboardAnalyticsIndexRouteImport } from './routes/dashboard/analytics/index'

const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailRoute = EmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/marketing/',
  path: '/marketing/',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceIndexRoute = FinanceIndexRouteImport.update({
  id: '/finance/',
  path: '/finance/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmIndexRoute = CrmIndexRouteImport.update({
  id: '/crm/',
  path: '/crm/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/settings/security',
  path: '/settings/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsBillingRoute = SettingsBillingRouteImport.update({
  id: '/settings/billing',
  path: '/settings/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingProductsRoute = MarketingProductsRouteImport.update({
  id: '/marketing/products',
  path: '/marketing/products',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceInvoicesRoute = FinanceInvoicesRouteImport.update({
  id: '/finance/invoices',
  path: '/finance/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceExpensesRoute = FinanceExpensesRouteImport.update({
  id: '/finance/expenses',
  path: '/finance/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorErrorRoute = ErrorErrorRouteImport.update({
  id: '/error/error',
  path: '/error/error',
  getParentRoute: () => rootRouteImport,
} as any)
const Error404Route = Error404RouteImport.update({
  id: '/error/404',
  path: '/error/404',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPortfolioRoute = DashboardPortfolioRouteImport.update({
  id: '/dashboard/portfolio',
  path: '/dashboard/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmDealsRoute = CrmDealsRouteImport.update({
  id: '/crm/deals',
  path: '/crm/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmContactsRoute = CrmContactsRouteImport.update({
  id: '/crm/contacts',
  path: '/crm/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmCompaniesRoute = CrmCompaniesRouteImport.update({
  id: '/crm/companies',
  path: '/crm/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMigrationIndexRoute = DashboardMigrationIndexRouteImport.update({
  id: '/dashboard/migration/',
  path: '/dashboard/migration/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCrmIndexRoute = DashboardCrmIndexRouteImport.update({
  id: '/dashboard/crm/',
  path: '/dashboard/crm/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAnalyticsIndexRoute = DashboardAnalyticsIndexRouteImport.update({
  id: '/dashboard/analytics/',
  path: '/dashboard/analytics/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/calendar': typeof CalendarRoute
  '/email': typeof EmailRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/test': typeof TestRoute
  '/voice': typeof VoiceRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/crm/companies': typeof CrmCompaniesRoute
  '/crm/contacts': typeof CrmContactsRoute
  '/crm/deals': typeof CrmDealsRoute
  '/dashboard/portfolio': typeof DashboardPortfolioRoute
  '/error/404': typeof Error404Route
  '/error/error': typeof ErrorErrorRoute
  '/finance/expenses': typeof FinanceExpensesRoute
  '/finance/invoices': typeof FinanceInvoicesRoute
  '/marketing/products': typeof MarketingProductsRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/crm': typeof CrmIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/finance': typeof FinanceIndexRoute
  '/marketing': typeof MarketingIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/dashboard/analytics': typeof DashboardAnalyticsIndexRoute
  '/dashboard/crm': typeof DashboardCrmIndexRoute
  '/dashboard/migration': typeof DashboardMigrationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/calendar': typeof CalendarRoute
  '/email': typeof EmailRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/test': typeof TestRoute
  '/voice': typeof VoiceRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/crm/companies': typeof CrmCompaniesRoute
  '/crm/contacts': typeof CrmContactsRoute
  '/crm/deals': typeof CrmDealsRoute
  '/dashboard/portfolio': typeof DashboardPortfolioRoute
  '/error/404': typeof Error404Route
  '/error/error': typeof ErrorErrorRoute
  '/finance/expenses': typeof FinanceExpensesRoute
  '/finance/invoices': typeof FinanceInvoicesRoute
  '/marketing/products': typeof MarketingProductsRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/crm': typeof CrmIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/finance': typeof FinanceIndexRoute
  '/marketing': typeof MarketingIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/dashboard/analytics': typeof DashboardAnalyticsIndexRoute
  '/dashboard/crm': typeof DashboardCrmIndexRoute
  '/dashboard/migration': typeof DashboardMigrationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/calendar': typeof CalendarRoute
  '/email': typeof EmailRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/test': typeof TestRoute
  '/voice': typeof VoiceRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/crm/companies': typeof CrmCompaniesRoute
  '/crm/contacts': typeof CrmContactsRoute
  '/crm/deals': typeof CrmDealsRoute
  '/dashboard/portfolio': typeof DashboardPortfolioRoute
  '/error/404': typeof Error404Route
  '/error/error': typeof ErrorErrorRoute
  '/finance/expenses': typeof FinanceExpensesRoute
  '/finance/invoices': typeof FinanceInvoicesRoute
  '/marketing/products': typeof MarketingProductsRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/crm/': typeof CrmIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/finance/': typeof FinanceIndexRoute
  '/marketing/': typeof MarketingIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/dashboard/analytics/': typeof DashboardAnalyticsIndexRoute
  '/dashboard/crm/': typeof DashboardCrmIndexRoute
  '/dashboard/migration/': typeof DashboardMigrationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/calendar'
    | '/email'
    | '/landing'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/test'
    | '/voice'
    | '/auth/forgot-password'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/crm/companies'
    | '/crm/contacts'
    | '/crm/deals'
    | '/dashboard/portfolio'
    | '/error/404'
    | '/error/error'
    | '/finance/expenses'
    | '/finance/invoices'
    | '/marketing/products'
    | '/settings/billing'
    | '/settings/profile'
    | '/settings/security'
    | '/crm'
    | '/dashboard'
    | '/finance'
    | '/marketing'
    | '/settings'
    | '/dashboard/analytics'
    | '/dashboard/crm'
    | '/dashboard/migration'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/calendar'
    | '/email'
    | '/landing'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/test'
    | '/voice'
    | '/auth/forgot-password'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/crm/companies'
    | '/crm/contacts'
    | '/crm/deals'
    | '/dashboard/portfolio'
    | '/error/404'
    | '/error/error'
    | '/finance/expenses'
    | '/finance/invoices'
    | '/marketing/products'
    | '/settings/billing'
    | '/settings/profile'
    | '/settings/security'
    | '/crm'
    | '/dashboard'
    | '/finance'
    | '/marketing'
    | '/settings'
    | '/dashboard/analytics'
    | '/dashboard/crm'
    | '/dashboard/migration'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/calendar'
    | '/email'
    | '/landing'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/test'
    | '/voice'
    | '/auth/forgot-password'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/crm/companies'
    | '/crm/contacts'
    | '/crm/deals'
    | '/dashboard/portfolio'
    | '/error/404'
    | '/error/error'
    | '/finance/expenses'
    | '/finance/invoices'
    | '/marketing/products'
    | '/settings/billing'
    | '/settings/profile'
    | '/settings/security'
    | '/crm/'
    | '/dashboard/'
    | '/finance/'
    | '/marketing/'
    | '/settings/'
    | '/dashboard/analytics/'
    | '/dashboard/crm/'
    | '/dashboard/migration/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CalendarRoute: typeof CalendarRoute
  EmailRoute: typeof EmailRoute
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  TestRoute: typeof TestRoute
  VoiceRoute: typeof VoiceRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  CrmCompaniesRoute: typeof CrmCompaniesRoute
  CrmContactsRoute: typeof CrmContactsRoute
  CrmDealsRoute: typeof CrmDealsRoute
  DashboardPortfolioRoute: typeof DashboardPortfolioRoute
  Error404Route: typeof Error404Route
  ErrorErrorRoute: typeof ErrorErrorRoute
  FinanceExpensesRoute: typeof FinanceExpensesRoute
  FinanceInvoicesRoute: typeof FinanceInvoicesRoute
  MarketingProductsRoute: typeof MarketingProductsRoute
  SettingsBillingRoute: typeof SettingsBillingRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
  CrmIndexRoute: typeof CrmIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  FinanceIndexRoute: typeof FinanceIndexRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  DashboardAnalyticsIndexRoute: typeof DashboardAnalyticsIndexRoute
  DashboardCrmIndexRoute: typeof DashboardCrmIndexRoute
  DashboardMigrationIndexRoute: typeof DashboardMigrationIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email': {
      id: '/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof EmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/': {
      id: '/marketing/'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/': {
      id: '/finance/'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/': {
      id: '/crm/'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/billing': {
      id: '/settings/billing'
      path: '/settings/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof SettingsBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/products': {
      id: '/marketing/products'
      path: '/marketing/products'
      fullPath: '/marketing/products'
      preLoaderRoute: typeof MarketingProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/invoices': {
      id: '/finance/invoices'
      path: '/finance/invoices'
      fullPath: '/finance/invoices'
      preLoaderRoute: typeof FinanceInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/expenses': {
      id: '/finance/expenses'
      path: '/finance/expenses'
      fullPath: '/finance/expenses'
      preLoaderRoute: typeof FinanceExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error/error': {
      id: '/error/error'
      path: '/error/error'
      fullPath: '/error/error'
      preLoaderRoute: typeof ErrorErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error/404': {
      id: '/error/404'
      path: '/error/404'
      fullPath: '/error/404'
      preLoaderRoute: typeof Error404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/portfolio': {
      id: '/dashboard/portfolio'
      path: '/dashboard/portfolio'
      fullPath: '/dashboard/portfolio'
      preLoaderRoute: typeof DashboardPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/deals': {
      id: '/crm/deals'
      path: '/crm/deals'
      fullPath: '/crm/deals'
      preLoaderRoute: typeof CrmDealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/contacts': {
      id: '/crm/contacts'
      path: '/crm/contacts'
      fullPath: '/crm/contacts'
      preLoaderRoute: typeof CrmContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/companies': {
      id: '/crm/companies'
      path: '/crm/companies'
      fullPath: '/crm/companies'
      preLoaderRoute: typeof CrmCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/migration/': {
      id: '/dashboard/migration/'
      path: '/dashboard/migration'
      fullPath: '/dashboard/migration'
      preLoaderRoute: typeof DashboardMigrationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/crm/': {
      id: '/dashboard/crm/'
      path: '/dashboard/crm'
      fullPath: '/dashboard/crm'
      preLoaderRoute: typeof DashboardCrmIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/analytics/': {
      id: '/dashboard/analytics/'
      path: '/dashboard/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  CalendarRoute: CalendarRoute,
  EmailRoute: EmailRoute,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  TestRoute: TestRoute,
  VoiceRoute: VoiceRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  CrmCompaniesRoute: CrmCompaniesRoute,
  CrmContactsRoute: CrmContactsRoute,
  CrmDealsRoute: CrmDealsRoute,
  DashboardPortfolioRoute: DashboardPortfolioRoute,
  Error404Route: Error404Route,
  ErrorErrorRoute: ErrorErrorRoute,
  FinanceExpensesRoute: FinanceExpensesRoute,
  FinanceInvoicesRoute: FinanceInvoicesRoute,
  MarketingProductsRoute: MarketingProductsRoute,
  SettingsBillingRoute: SettingsBillingRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
  CrmIndexRoute: CrmIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  FinanceIndexRoute: FinanceIndexRoute,
  MarketingIndexRoute: MarketingIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  DashboardAnalyticsIndexRoute: DashboardAnalyticsIndexRoute,
  DashboardCrmIndexRoute: DashboardCrmIndexRoute,
  DashboardMigrationIndexRoute: DashboardMigrationIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
