import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

function generateCSS() {
  try {
    console.log('🎨 Generating CSS Variables...');

    // Read tokens
    const tokenPath = path.join(__dirname, '..', 'design-system', 'design-tokens.json');
    const tokens = JSON.parse(fs.readFileSync(tokenPath, 'utf8'));

    let css = `/**
 * CoreFlow360 V4 Design System - CSS Variables
 * Generated from design-tokens.json
 * DO NOT EDIT THIS FILE DIRECTLY
 */

:root {
`;

    // Add key CSS variables for immediate use
    css += `  /* Colors */
  --color-white: #ffffff;
  --color-black: #000000;
  --color-primary: #2563eb;
  --color-primary-hover: #1d4ed8;
  --color-success: #16a34a;
  --color-warning: #d97706;
  --color-error: #dc2626;

  /* Gray scale */
  --color-gray-50: #f8fafc;
  --color-gray-100: #f1f5f9;
  --color-gray-200: #e2e8f0;
  --color-gray-300: #cbd5e1;
  --color-gray-500: #64748b;
  --color-gray-600: #475569;
  --color-gray-700: #334155;
  --color-gray-800: #1e293b;
  --color-gray-900: #0f172a;

  /* Spacing (8px grid) */
  --spacing-xs: 0.25rem; /* 4px */
  --spacing-sm: 0.5rem;  /* 8px */
  --spacing-md: 1rem;    /* 16px */
  --spacing-lg: 1.5rem;  /* 24px */
  --spacing-xl: 2rem;    /* 32px */
  --spacing-2xl: 2.5rem; /* 40px */
  --spacing-3xl: 3rem;   /* 48px */

  /* Typography */
  --font-family-sans: 'Inter', ui-sans-serif, system-ui, sans-serif;
  --font-size-xs: 0.75rem;   /* 12px */
  --font-size-sm: 0.875rem;  /* 14px */
  --font-size-base: 1rem;    /* 16px */
  --font-size-lg: 1.125rem;  /* 18px */
  --font-size-xl: 1.25rem;   /* 20px */
  --font-size-2xl: 1.5rem;   /* 24px */
  --font-size-3xl: 1.875rem; /* 30px */
  --font-size-4xl: 2.25rem;  /* 36px */

  /* Border radius */
  --radius-none: 0;
  --radius-sm: 0.125rem; /* 2px */
  --radius-base: 0.25rem; /* 4px */
  --radius-md: 0.375rem; /* 6px */
  --radius-lg: 0.5rem;   /* 8px */
  --radius-xl: 0.75rem;  /* 12px */
  --radius-full: 9999px;

  /* Shadows */
  --shadow-sm: 0 1px 2px 0 rgba(0, 0, 0, 0.05);
  --shadow-base: 0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06);
  --shadow-md: 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06);
  --shadow-lg: 0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05);

  /* Semantic colors */
  --bg-canvas: var(--color-white);
  --bg-surface: var(--color-gray-50);
  --bg-muted: var(--color-gray-100);

  --text-primary: var(--color-gray-900);
  --text-secondary: var(--color-gray-600);
  --text-muted: var(--color-gray-500);
  --text-inverse: var(--color-white);

  --border-default: var(--color-gray-200);
  --border-muted: var(--color-gray-100);
  --border-strong: var(--color-gray-300);

  /* Component tokens */
  --btn-primary-bg: var(--color-primary);
  --btn-primary-bg-hover: var(--color-primary-hover);
  --btn-primary-text: var(--text-inverse);
  --btn-padding-x: var(--spacing-md);
  --btn-padding-y: var(--spacing-sm);
  --btn-radius: var(--radius-md);

  --input-bg: var(--bg-canvas);
  --input-border: var(--border-default);
  --input-border-focus: var(--color-primary);
  --input-text: var(--text-primary);
  --input-placeholder: var(--text-muted);
  --input-padding-x: var(--spacing-sm);
  --input-padding-y: var(--spacing-sm);
  --input-radius: var(--radius-base);

  --card-bg: var(--bg-surface);
  --card-border: var(--border-muted);
  --card-padding: var(--spacing-lg);
  --card-radius: var(--radius-lg);
  --card-shadow: var(--shadow-base);

  /* Transitions */
  --transition-fast: 150ms;
  --transition-base: 250ms;
  --transition-slow: 400ms;
  --ease-in-out: cubic-bezier(0.4, 0, 0.2, 1);
}

/* Dark theme */
[data-theme="dark"] {
  --bg-canvas: var(--color-gray-900);
  --bg-surface: var(--color-gray-800);
  --bg-muted: var(--color-gray-700);

  --text-primary: var(--color-gray-100);
  --text-secondary: var(--color-gray-300);
  --text-muted: var(--color-gray-400);
  --text-inverse: var(--color-gray-900);

  --border-default: var(--color-gray-700);
  --border-muted: var(--color-gray-800);
  --border-strong: var(--color-gray-600);

  --input-bg: var(--bg-canvas);
  --card-bg: var(--bg-surface);
}

/* Utility classes */
.sr-only {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  white-space: nowrap;
  border: 0;
}

.theme-transition * {
  transition: background-color var(--transition-base) var(--ease-in-out),
              border-color var(--transition-base) var(--ease-in-out),
              color var(--transition-base) var(--ease-in-out);
}

.focus-ring:focus {
  outline: 2px solid var(--color-primary);
  outline-offset: 2px;
}
`;

    css += '}\n';

    // Write CSS file
    const cssPath = path.join(__dirname, '..', 'design-system', 'tokens.css');
    fs.writeFileSync(cssPath, css);

    console.log('✓ CSS variables generated:', cssPath);
    console.log('✓ Ready for website and Figma integration!');

    return true;
  } catch (error) {
    console.error('✖ CSS generation failed:', error.message);
    return false;
  }
}

generateCSS();